/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommunicationListRelationFilter } from "../../communication/base/CommunicationListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DataRequestListRelationFilter } from "../../dataRequest/base/DataRequestListRelationFilter";
import { DataUploadListRelationFilter } from "../../dataUpload/base/DataUploadListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PrivacyAgreementListRelationFilter } from "../../privacyAgreement/base/PrivacyAgreementListRelationFilter";

@InputType()
class CompanyWhereInput {
  @ApiProperty({
    required: false,
    type: () => CommunicationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CommunicationListRelationFilter)
  @IsOptional()
  @Field(() => CommunicationListRelationFilter, {
    nullable: true,
  })
  communications?: CommunicationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DataRequestListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DataRequestListRelationFilter)
  @IsOptional()
  @Field(() => DataRequestListRelationFilter, {
    nullable: true,
  })
  dataRequests?: DataRequestListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DataUploadListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DataUploadListRelationFilter)
  @IsOptional()
  @Field(() => DataUploadListRelationFilter, {
    nullable: true,
  })
  dataUploads?: DataUploadListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  industry?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  privacyAgreement?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PrivacyAgreementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PrivacyAgreementListRelationFilter)
  @IsOptional()
  @Field(() => PrivacyAgreementListRelationFilter, {
    nullable: true,
  })
  privacyAgreements?: PrivacyAgreementListRelationFilter;
}

export { CompanyWhereInput as CompanyWhereInput };
